import type { Metadata } from "next";
import HeroSection from "@/components/sections/HeroSection";
import DataStrip from "@/components/sections/DataStrip";
import ManifestoSection from "@/components/sections/ManifestoSection";
import ComparisonSection from "@/components/sections/ComparisonSection";
import ValueStackSection from "@/components/sections/ValueStackSection";
import CalculatorSection from "@/components/sections/CalculatorSection";
import CasesPreview from "@/components/sections/CasesPreview";
import ArticlesPreview from "@/components/sections/ArticlesPreview";
import QualifySection from "@/components/sections/QualifySection";
import CTAFinal from "@/components/sections/CTAFinal";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const isRo = locale === "ro";

  return {
    title: isRo
      ? "High-Up Labs — Performance Marketing pe Comision"
      : "High-Up Labs — Commission-Based Performance Marketing",
    description: isRo
      ? "Primul model comision-only din Romania. 5-10% din vanzarile aduse de reclame. Zero retainer. 90 zile garantie."
      : "Romania's first commission-only model. 5-10% of ad-generated sales. Zero retainer. 90-day guarantee.",
    alternates: {
      canonical: `https://highuplabs.ro/${locale}`,
      languages: {
        "ro-RO": "https://highuplabs.ro/ro",
        "en-US": "https://highuplabs.ro/en",
      },
    },
  };
}

export async function generateStaticParams() {
  return [{ locale: "ro" }, { locale: "en" }];
}

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isRo = locale === "ro";

  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "High-Up Labs",
    alternateName: "STEFAN SERBAN INVESTITII IMOBILIARE SRL",
    url: "https://highuplabs.ro",
    logo: "https://highuplabs.ro/logo.png",
    description: isRo
      ? "Primul model comision-only din Romania. 5-10% din vanzarile aduse de reclame."
      : "Romania's first commission-only performance marketing agency.",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Str. Lucian Blaga 12",
      addressLocality: "Pitești",
      addressRegion: "Argeș",
      postalCode: "110177",
      addressCountry: "RO",
    },
    contactPoint: {
      "@type": "ContactPoint",
      telephone: "+40-725-358-757",
      contactType: "Business",
      email: "business@highuplabs.ro",
    },
    sameAs: [
      "https://www.facebook.com/highuplabs",
      "https://www.instagram.com/highuplabs",
    ],
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: isRo ? "Cât costă colaborarea?" : "How much does collaboration cost?",
        acceptedAnswer: {
          "@type": "Answer",
          text: isRo
            ? "5-10% din vanzarile generate direct de reclame. Zero retainer, zero costuri ascunse."
            : "5-10% of sales directly generated by ads. Zero retainer, zero hidden costs.",
        },
      },
      {
        "@type": "Question",
        name: isRo ? "Cât durează până la primele rezultate?" : "How long until first results?",
        acceptedAnswer: {
          "@type": "Answer",
          text: isRo
            ? "Primele semnale clare apar în 14-30 de zile. Scalingul consistent începe după 60-90 de zile."
            : "First clear signals appear in 14-30 days. Consistent scaling starts after 60-90 days.",
        },
      },
      {
        "@type": "Question",
        name: isRo ? "Ce se întâmplă dacă nu sunteți mulțumiți?" : "What if you're not satisfied?",
        acceptedAnswer: {
          "@type": "Answer",
          text: isRo
            ? "Oferim garanție de 90 de zile. Dacă nu atingem targetul POAS agreat, luna a 4-a este gratis."
            : "We offer a 90-day guarantee. If we don't reach the agreed POAS target, month 4 is free.",
        },
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
      />
      <script
        type="application/ld+json"


        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <HeroSection />
      <DataStrip />
      <ManifestoSection />
      <ComparisonSection />
      <ValueStackSection />
      <CalculatorSection />
      <CasesPreview />
      <ArticlesPreview />
      <QualifySection />
      <CTAFinal />
    </>
  );
}
